[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = ".output/public"
  
  # Build command for Nuxt static generation
  command = "npm run generate"

[build.environment]
  # Node.js version - using 20 for Nuxt 4 compatibility
  NODE_VERSION = "20"

# Redirect rules for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for all files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# HTML files - no caching to ensure updates
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self';"

# CSS files - short cache with versioning
[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# JavaScript files - short cache
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# Media files - longer cache but not immutable
[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
